export const RESET_RESULTS = 'RESET_RESULTS'
export const PUSH_RESULTS = 'PUSH_RESULTS'
export const TOGGLE_AUTOCOMPLETE = 'TOGGLE_AUTOCOMPLETE'
export const RECEIVE_AUTOCOMPLETE = 'RECEIVE_AUTOCOMPLETE'